### ISSUE TITLE
Toggle para habiltar OCR não é exibido

### ISSUE THREAD

**Issue by danroxha** [edu-look/look-api#22]
![image](https://github.com/edu-look/look-api/assets/38236602/76156673-cf82-4edd-8287-aa196352478e)

https://github.com/edu-look/look-api/blob/c1205e9c6f1b0bdd1c5f87e4f3619b781525439b/src/main/resources/templates/edit.html#L30

Deve exbir o toggle junto com a seleção de paginas. Não apenas quando tiver conteúdo

**Comment by YtaloSauham** [comment]
Corrigido.
